### ISSUE TITLE
Eliminate use of binaries to get node info

### ISSUE THREAD

**Issue by MadhavJivrajani** [pesos/heiko#10]
Hey, so I was trying to understand how `heiko` is getting node information like CPU and RAM usage and things like that.

I noticed that in a lot of places it's making use of binaries such as `lscpu` and free. That's actually a really convenient way to do it, but I recently found out that in quite a few cases, binaries like `lscpu` aren't installed by default. So that might cause an issue. Another improvement that `heiko` might be able to achieve is, since it's going to be checking for these details multiple times, you'll have to load the binary I to memory atleast once. Instead what you could do is, you could maybe just read the info directly from the source itself that binaries like `lscpu` and free use. 

So for example, for `lscpu`, the info you need can be gotten from `/proc/cpuinfo` and
`/sys/devices/system/cpu*/cpufreq/cpuinfo_max_freq`

For `free` you can get the info from `/proc/meminfo`

**Comment by Samyak2** [comment]
This is a much better idea. We had initially used those binaries because we found that the `/sys` FS was not readable on termux devices (mobile phones). Upon further inspection, it appears that while `/sys` is restricted from using something like `ls` on it, the actual files are available. For example, the files you listed (`cat /sys/devices/system/cpu/cpu*/cpufreq/cpuinfo_max_freq` and `cat /proc/cpuinfo`) are readable.

---

I believe the changes would need to go here: https://github.com/pesos/heiko/blob/b2365c591094e849efe99ed8c1671199d0c4019e/heiko/utils/load.py#L28-L59

The commands (in `conn.run`) would have to be replaced with `cat <filename>` (i'm not sure if there's a way to directly read files over SSH). The regexes (and patterns) will also have to be changed.

Is this the solution you were suggesting?

**Comment by MadhavJivrajani** [comment]
Yep! That's right. I can take this up!

**Comment by Samyak2** [comment]
Thanks!

**Comment by MadhavJivrajani** [comment]
Hey, in this function, did you want to the MHz value which came last in the list? Or is max cpu freq and cpu freq supposed to be 2 separate keys in the `cpu` dict?
https://github.com/pesos/heiko/blob/b2365c591094e849efe99ed8c1671199d0c4019e/heiko/utils/load.py#L73-L85

**Comment by Samyak2** [comment]
Oh F, I had not noticed that. I think that should be the max MHz since we use it to estimate the computing power of that node (load average is used to estimate current load on the node instead of the current CPU freq). @psiayn can you confirm if this is what you intended here?

**Comment by psiayn** [comment]
Hi, sorry for late reply ( i haven't been checking github in a while ). Looks like I did something stupid there 😞. It's best to stick with max not just cpu MHz as there would be massive discrepancies in the CPU MHz.
